variables:
    TWINE_USERNAME: SECURE
    TWINE_PASSWORD: SECURE
    TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/

stages:
  - test
  - deploy

test:
  image: python:3
  stage: test
  script:
    - pip install .
    - python setup.py test --addopts "--cov=srim"

deploy_pypi:
  image: python:3
  stage: deploy
  script:
    - pip install -U twine setuptools
    - pip list
    - python setup.py sdist bdist_wheel
    - twine upload dist/*.tar.gz
    - twine upload dist/*.whl
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
