variables:
    TWINE_USERNAME: SECURE
    TWINE_PASSWORD: SECURE
    TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
    ANACONDA_USERNAME: SECURE
    ANACONDA_TOKEN: SECURE
    DOCKER_PASSWORD: SECURE
    DOCKER_USERNAME: SECURE


stages:
  - test
  - deploy

test:
  image: python:3
  stage: test
  script:
    - pip install .
    - python setup.py test --addopts "--cov=srim"

deploy_pypi:
  image: python:3
  stage: deploy
  script:
    - pip install -U twine setuptools
    - python setup.py sdist bdist_wheel
    - twine upload dist/*.tar.gz
    - twine upload dist/*.whl
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)

deploy_conda:
  image: continuumio/miniconda3:latest
  stage: deploy
  script:
    - conda install anaconda-client setuptools conda-build -y
    - python setup.py bdist_conda
    - anaconda -t $ANACONDA_TOKEN upload -u $ANACONDA_USERNAME /opt/conda/conda-bld/linux-64/pysrim*.tar.bz2
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)

deploy_docker_srim:
  image: docker:git
  services:
    - docker:dind
  script:
    - export DOCKER_IMAGE="costrouc/srim"
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_IMAGE:latest -f Dockerfile.srim .
    - docker push $DOCKER_IMAGE:latest
  only:
    - /^srim$/ # trigger to build srim dockerfile
